---
- hosts: localhost
  name: create and run example docker application stack
  
  tasks:
  - name: Manage viewer docker image
    docker_image:
      name: viewer
      state: present
      build_path: "{{ playbook_dir }}/viewer"
      dockerfile: viewer-2.dockerfile
    register: viewer_image

  - name: Manage the creator docker image
    docker_image:
      name: creator
      state: present
      build_path: "{{ playbook_dir }}/creator"
      dockerfile: creator.dockerfile
    register: creator_image

  - name: Ensure docker network present
    docker_network:
      name: BeanNet
      state: present

  - name: Initialize database container
    docker_container:
      name: db
      image: mysql:5.7.22
      state: started
      networks:
        - name: BeanNet
      ports:
        - 3306
      env:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: DockBeanBiz
      volumes:
        - "{{ playbook_dir }}/db/initdb.d:/docker-entrypoint-initdb.d"
    register: db_meta

  - name: get mysql IP address
    command: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' db"
    register: db_ip

  - name: Wait for db to become available
    wait_for:
      host: "{{ mariadb_ip_address.stdout }}"
      port: 3306
      state: started
      delay: 5
      connect_timeout: 15
      timeout: 30
    register: db_running
    until: db_running is success
    retries: 10
  
  - name: Start the viewer
    docker_container:
      name: viewer
      image: viewer
      restart_policy: always
      networks:
        - name: BeanNet
      ports:
        - "5000:5000"
      volumes:
        - "{{ playbook_dir }}/viewer/source:/srv/viewer"
    register: viewer

  - name: Start the creator
    docker_container:
      name: creator
      image: creator
      restart_policy: no
      networks:
        - name: BeanNet
      volumes:
        - "{{ playbook_dir }}/creator/source:/home/creator"
    register: creator