# docker-compose file for the "internal" application stack
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  viewer:
    image: viewer
    restart: always
    ports:
      - 5000:5000
