# docker-compose file for the "internal" application stack
version: '3.2'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DockBeanBiz
    volumes:
      - type: bind
        source: ./db/initdb.d
        target: /docker-entrypoint-initdb.d
  viewer:
    # The viewer image currently must be manually built
    # docker build -f viewer.dockerfile --tag viewer .
    build:
      context: viewer/
      dockerfile: viewer-2.dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./viewer/source
        target: /srv/viewer
