# docker-compose file for the "internal" application stack
version: '3.2'

services:
  db:
    image: mysql:5.7.22
    # command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DockBeanBiz
    volumes:
      - type: bind
        source: ./db/initdb.d
        target: /docker-entrypoint-initdb.d
  viewer:
    build:
      context: viewer/
      dockerfile: viewer-2.dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./viewer/source
        target: /srv/viewer
  creator:
    build:
      context: creator/
      dockerfile: creator.dockerfile
    restart: always
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./creator/source
        target: /home/creator
